import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>R3F Under the Hood</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>R3F Under the Hood</h1>
        <iframe
          className={styles.video}
          width="640"
          height="360"
          src="https://www.youtube.com/embed/DPl34H2ISsk"
          title="I wish I knew this before using React Three Fiber"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowFullScreen
        ></iframe>

        <div className={styles.grid}>
          <Link href="/three">
            <div className={styles.card}>
              <h2>Three.js Demo &rarr;</h2>
              <p>View the Three.js part of the demo</p>
            </div>
          </Link>

          <Link href="/r3f">
            <div className={styles.card}>
              <h2>R3F Demo &rarr;</h2>
              <p>View the React Three Fiber part of the demo</p>
            </div>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
